
quarkus:

  application:
    name: actor-service

  resteasy-reactive:
    path: /api

  otel:
    exporter:
      otlp:
        traces:
          endpoint: http://localhost:4317
#          headers: authorization=Bearer my_secret

  datasource:
    db-kind: postgresql
    username: postgres
    password: 12345
    reactive:
      url: vertx-reactive:postgresql://localhost:15432/dvdrental
    metrics:
      enabled: true

  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    log:
      bind-parameters: true
      sql: true

  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    min-level: TRACE

  http:
    port: 18181

